### PR TITLE
Fix title lengths, remove hardcoded en-us links

### PR DESCRIPTION
**Pull request by mattwojo**

### CODE REVIEW

**Comment by mattwojo** [comment]
*Adding one more change to replace all of the "http://" links with "https://"

**Comment by jessemcculloch** [comment]
Hey @mattwojo - Looks like the index-hidden page can probably go away.  Can you do that in this PR as well?

**Comment by mattwojo** [comment]
Oops - those dup files got added back in - just pushed a fix, along with fixes for those other warnings

**Comment by mattwojo** [comment]
Thanks!!

**Pull request merged**
