### PR TITLE
Azure speech services mrtk2.7 update

### PR DESCRIPTION
**Pull request by veeruby-developer**
- Updated MRTK Version to 2.7.0
- Updated the tutorials to support Unity 2019 Legacy WSA, XRSDK and Unity 2020 OpenXR and XRSDK.
- Tested Azure Speech Services tutorial series for MRTK 2.7.0 with Unity 2019 Legacy WSA, XRSDK and Unity 2020 OpenXR and XRSDK.
- Screenshots updated.
- Fixed Issue #298

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Vinayak0706 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @jessemcculloch

**Comment by PRMerger13** [comment]
@Vinayak0706 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @jessemcculloch

**Comment by PRMerger13** [comment]
@varunsiddaraju : Thanks for your contribution! The author(s) have been notified to review your proposed change. @jessemcculloch

**Comment by PRMerger12** [comment]
@varunsiddaraju : Thanks for your contribution! The author(s) have been notified to review your proposed change. @jessemcculloch

**Comment by PRMerger14** [comment]
@Vinayak0706 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @jessemcculloch

**Comment by veeruby-developer** [comment]
Closing this PR, since new PR is created in MicrosoftDocs/mixed-reality-pr, repo.

**Pull request closed without merging**
