### PR TITLE
Readability update

### PR DESCRIPTION
**Pull request by martinwilter**
Requested from https://github.com/MicrosoftDocs/mixed-reality/pull/2324.

### CODE REVIEW

**Comment by hferrone** [comment]
Great! I'll take a look.

**Comment by hferrone** [comment]
@martinwilter Can you somehow add this readability update into PR 2324?

**Comment by martinwilter** [comment]
> @martinwilter Can you somehow add this readability update into PR 2324?

@hferrone, I can, but would need push access to your branch https://github.com/hferrone/mixed-reality/tree/ModuleUpdate.

**Comment by martinwilter** [comment]
> > @martinwilter Can you somehow add this readability update into PR 2324?
> 
> @hferrone, I can, but would need push access to your branch https://github.com/hferrone/mixed-reality/tree/ModuleUpdate.

@hferrone, alternatively, if you want, I can make a PR to your branch. Once you merge my PR into your branch, your PR https://github.com/MicrosoftDocs/mixed-reality/pull/2324 will automatically be updated with the changes you merged in from my branch.

**Comment by hferrone** [comment]
Perfect, please do the second option.

**Comment by martinwilter** [comment]
Hi @hferrone,

I created a new PR https://github.com/hferrone/mixed-reality/pull/1 against your fork.

Closing this PR.

**Pull request closed without merging**
