### PR TITLE
Tidied up some of the sample code

### PR DESCRIPTION
**Pull request by peted70**
- removed unused using statements
- fixed compile warnings
- made the code more succinct and I think, more readable
(happy to make changes to the other samples for consistency - just checking consensus on this first)

### CODE REVIEW

**Comment by peted70** [comment]
Wondering if the sample code is in a repo somewhere and shouldn't be referenced in this documentation rather than embedded?

**Comment by mattzmsft** [comment]
@elliotmoule @StefanoDeflorio are you guys comfortable with these changes? And want to answer @peted70 about the sample code being in a repo somewhere?

**Comment by elliotmoule** [comment]
Hi @peted70 , thank you for your contributions, not only now but also previously :) 
We are pretty happy with most of your changes, and do think that the labs would benefit from them. 

That being said, the labs have been built as hands-on learning and understanding exercises. As this is the case, we have made a point of always using explicit types with the labs, so that the user, rather than the compiler, understands what has been used and why, As such, we would be much happier with your changes, if the use of the implicit type **var** was replaced with the their explicit types. 

Regarding sample code, as mentioned, because the labs are hands-on learning and understanding exercises, the code and document go hand-in-hand. This helps people not only put the lab together, but understand the *how* and *why*, in turn empowering them to create their own apps with the Azure services. So, to use the code separately from the document would defeat the purpose of them having been created in the first place. 

We are very committed to making the labs the best they can be, and welcome contributions, updates, and improvements, provided they do not take away from the purpose, and know that you feel the same. We would welcome you to contribute to the labs further, provided the above is kept in mind. 

Thanks again, and hoping to work with you more in the future. 

Regards,

Elliot Moule.

**Comment by peted70** [comment]
Hi Elliot,

Agree with the vars - esp. when reading the code as a document. I have committed the changes.

**Comment by mattzmsft** [comment]
Thanks everyone! Awesome teamwork!

**Pull request merged**
