### PR TITLE
[1624627] Azure Machine Learning rebranding.

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
This is for [1624627](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1624627).

If you got a GitHub notification for this, you can disregard. We'll get sign off from Peter Lu.

### CODE REVIEW

**Comment by TimShererWithAquent** [comment]
@PeterCLu - this is ready for review. 

I'm not sure why there isn't an acrolynx report for this PR. I'll follow up, if necessary, at the merge.

**Comment by PeterCLu** [comment]
@TimShererWithAquent , looks good as far the changes go. You might have to close and reopen the PR, That usually resolves any build bugs. Thanks.

**Comment by TimShererWithAquent** [comment]
#sign-off

**Comment by TimShererWithAquent** [comment]
Per Peter's suggestion, I'm closing and reopening this because I expected an Acrolinx report. 

That said, I've never worked in this repo, so maybe it doesn't run automatically.

**Comment by TimShererWithAquent** [comment]
And reopen.

**Comment by TimShererWithAquent** [comment]
@jessemccullock - do you own this repo? we are trying to get this merged - any help would be appreciated.

**Pull request merged**
