### PR TITLE
Updates to error descriptions and outdated Windows versions

### PR DESCRIPTION
**Pull request by ErrorRaffyline0**
In a DM with Ryan Handy (Quality Program Manager for HP VR) (u/Voodooimaxx on Reddit), I reported an issue that leads to error 13-14 on select system configurations. He told me that he would forward it to Microsoft and Nvidia (he likely misunderstood that I was testing on an AMD Radeon RX 580). This would mean this issue has been sent through developer channels, or will be in the near future. If you want to verify the validity of this bug being investigated, feel free to contact him (Microsoft probably has better channels to contact him, considering he only uses his Reddit once a month). 

Also, if anyone can do it, please make the layout consistent. Error messages are quoted in some descriptions, but left out in others, the order of the steps are shown with numbers in some descriptions, in other descriptions dots are used for steps, etc.

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@TheJokingTeen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TheJokingTeen** [comment]
@MaxWang-MS Could you review this PR? I am aware that adding this error information might not be good, as the issue hasn't been acknowledged, but this commit also includes clarifications to existing issues that make the page more accurate.

**Comment by TheJokingTeen** [comment]
About the recent commit to the branch, I removed my additions to error 13-14 and made it match commit 88ff3d5 of the MicrosoftDocs:docs branch. Please note I still think my previous commit should be used, but this one is here in case MSFT doesn't want to merge the info as the additional info about the 13-14 error may be controversial. 

Please consider using the previous commit instead, unless it is out of the question to add the changes about error 13-14.

**Comment by ErrorRaffyline0** [comment]
@MaxWang-MS Please consider reviewing this, @qianw211 seems to be inactive.

**Comment by MaxWang-MS** [comment]
Hi @ErrorRaffyline0, just to clarify this PR is now only about cleaning up some formatting and updating the Windows version being referenced right?

**Comment by ErrorRaffyline0** [comment]
> Hi @ErrorRaffyline0, just to clarify this PR is now only about cleaning up some formatting and updating the Windows version being referenced right?

@MaxWang-MS Hi! Thanks for the reply :), I at first thought it'd be a good idea to include info about an ongoing issue, but I had some misleading mentions about it being under investigation (I assumed due to the person I was in contact with). I have now removed that part and added better instructions for error 13-14 and I have also improved the formatting and the mentions about Windows versions.

**Pull request merged**
