### PR TITLE
Design Guideline for HandCoach UX

### PR DESCRIPTION
**Pull request by grayclee**
This is the design guideline for handCoach

### CODE REVIEW

**Comment by grayclee** [comment]
Ok, I was curious about that... cause I don’t need it for my section. I’ll put it back tomorrow :) thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cre8ivepark** [comment]
@grayclee Grab the logo file from this repo/master and put it(or overwrite) into your branch, commit and push.

**Comment by grayclee** [comment]
Hmmm I have it in my project and even when I replace it says my working tree is clean

Grace

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by grayclee** [comment]
I added back the Unreal Logo, from Microsoft master Branch.

**Comment by cre8ivepark** [comment]
@jessemcculloch @grayclee Fixed the merge issue and opened a new PR #2049

**Pull request closed without merging**
