### PR TITLE
Base Tutorials Overhaul

### PR DESCRIPTION
**Pull request by martinwilter**
* Major update to [Getting started tutorials](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base), [Azure Spatial Anchor tutorials](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-asa-ch1), and [Multi-user capabilities tutorials](https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-sharing(photon)-ch1)
* Replace main model 'TheModule' (LunarModule) with 'MarsCuriosityRover' model
* Change flow to build out the experience throughout the tutorial
* Upgrade to MRTK 2.4.0
* Upgrade to Unity 2019.3

### CODE REVIEW

**Comment by martinwilter** [comment]
Hi @hferrone,

Couple of questions:

1. Are those 'Can't preserve document ID for redirected file' suggestions ok as is? I think they will be resolved when merged in? Or do you want me to change the 'redirect_document_id' to 'false'? (Ideally, it should be true).
3. For the 'duplicate-h1s' suggestions, would you like me to update those headers? We have created an 'Introduction' page for each tutorial series, which is why there are duplicate headers. Also, the Unreal tutorial series is using the same headers as our Getting Started Started tutorials 'mr-learning-base-02.md', but we can change ours if necessary.

**Comment by hferrone** [comment]
Hi @martinwilter 

I think the suggestions are fine as-is, unless @jessemcculloch disagrees. 

However, the mrlearning-base filenames are now mismatched, ie mrlearning-base-ch1.md is the second tutorial in the series :( 

Can you also add red box callouts to all screenshots?

**Comment by martinwilter** [comment]
Hi @hferrone,

> However, the mrlearning-base filenames are now mismatched, ie mrlearning-base-ch1.md is the second tutorial in the series :(

Actually, mrlearning-base-ch1.md was deleted with commit https://github.com/MicrosoftDocs/mixed-reality/pull/2320/commits/83b3c9bd0d074ff3e9d4df93c3874b858b4a4c33. All mrlearning-base, mrlearning-asa, and mrlearning-sharing .md files are deleted and have been replaced with mr-learning-base-01.md etc. This was done to align the file names with the general file name naming convention in the repo.

Re the mismatch, the confusion here might be that the live tutorials are improperly numbered, the second tutorial starts as mr-learning-base-01.md, while the first tutorial is simply mr-learning-base.md which causes the .md number to not match the tutorial number, something that can be very confusing both for readers and creators/maintainers:

image

We can change it back, but I recommend keeping the fix we provided.
__

> Can you also add red box callouts to all screenshots?

We don't use red box callouts because they are distracting, they don't exist in Unity, and they limit the reader's learning.  If you present the reader with a red 'kill box' for each action they need to take, the reader will end up learning a lot less because there will be very limited learning by recollection, which is one of the most efficient learning styles.

Instead, we focus on highly accurate and informative images, meaning each image is exactly as Unity will look at that exact point in the tutorial. Not just the particular item the reader is working on, but the entire Unity editor. This allows the reader to continuously be able to cross-reference any visible part of the Unity editor, including previous, current, and future steps, helping the reader be more successful.

Additionally, we embed native Unity highlights on top of the base screenshots. Here's an example screenshot from Photoshop of image base-09-section3-step1-6.png, layer 2 and 3 are masked on top of layer 1, layer 1 maximizes the use of native Unity highlights by making sure the mouse is hovering over the RoverExplorer object when the screenshot is taken:

image

By the way, if you look at the live tutorial, this is the pedagogic approach we took for those tutorials and it seems to have been successful. There have been no issues requesting red boxes since we implemented these changes to the live tutorials, while before that approach, there were issues asking for them to be changed, for example, thicker box lines.

This is the methodology/thinking we've applied to these three tutorial series, hope it makes sense, but if you still feel red box callouts are needed, let me know.

**Comment by hferrone** [comment]
@martinwilter Sounds good. 

@jessemcculloch Can you merge this pull into ModuleUpdate so I can add my changes? It still won't let me push to this PR.

**Pull request merged**
