### PR TITLE
v-tea-CI-103422-B

### PR DESCRIPTION
**Pull request by Teresa-Motiv**
Edits and TOC changes

### CODE REVIEW

**Comment by jessemcculloch** [comment]
This is still in draft.  Is it waiting for something in particular?  Just want to make sure we are not missing getting it merged.

Thanks,
Jesse

**Comment by Teresa-Motiv** [comment]
> This is still in draft. Is it waiting for something in particular? Just want to make sure we are not missing getting it merged.
> 
> Thanks,
> Jesse

This PR has been put on hold until some larger issues are resolved with the HoloLens docs. Current due date is 8/30/19. Should I close out this PR (keeping the branch on my fork) and open a new one when work resumes?

Thanks,
Teresa A.

**Comment by jessemcculloch** [comment]
Nope, no need to close it.  The context helps.  Appreciate it!

**Comment by Teresa-Motiv** [comment]
All content related to CI 103422 is being moved over to Sarah Cooley's reorganization project on Windows-Docs-pr (hololens2-release branch). This PR is no longer needed.

**Pull request closed without merging**
