### PR TITLE
C109177: Escaping mock URLs

### PR DESCRIPTION
**Pull request by v-maudel**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Description: All hyperlinks are mock hyperlinks and should not be rendered. Please consider adding a backslash on all hyperlinks to prevent link rendering

### CODE REVIEW

**Comment by v-maudel** [comment]
Hi @JonMLyons, could you please approve and merge this PR if agree?
regards

**Comment by v-maudel** [comment]
Hi @JonMLyons , We know that, but it seems to be here as a reference or example, if it really needs to work as a clickable link, it should be in link md format [reference name](url).
Please, confirm if which way it should be displayed and I make the changes. 

Regards.

**Comment by jessemcculloch** [comment]
I have put the link in the correct format and will be merging this PR.

Thanks All

**Comment by v-maudel** [comment]
Thanks @jessemcculloch

**Pull request merged**
