### PR TITLE
New Design Guidline on the Hand Menu

### PR DESCRIPTION
**Pull request by nbarragan23**
New Design Guidline on the Hand Menu

### CODE REVIEW

**Comment by rwinj** [comment]
I made some edits - Fixed metadata, See also, spacing and sentence case.

**Comment by jessemcculloch** [comment]
@nbarragan23  -  I still can't merge this PR, as it will remove our gitignore file.

**Comment by nbarragan23** [comment]
How can I help on this?

**Comment by nbarragan23** [comment]
@jessemcculloch Restored .gitignore file! Thanks!

**Pull request merged**
