### PR TITLE
Update Unity version recommendation

### PR DESCRIPTION
**Pull request by bradweiers**

### CODE REVIEW

**Comment by mattzmsft** [comment]
Hey @bradweiers, I took a different approach here and instead of linking to a specific version of Unity, I pointed back to the [Install the tools](install-the-tools.md) article for the latest recommended version (currently 2017.4). However, I noticed that the rest of this article (even after your edits) still includes links to porting guides on Unity's website that are specific to 2017.2 and the article even has a line about "staying on 2017.2." Is that true? Or can we remove all the 2017.2 specific links and notes and point to something more evergreen?

Thanks,
Matt

**Comment by bradweiers** [comment]
Yes I'll try and figure out a way to make it last a little longer

**Comment by bradweiers** [comment]
OK that should do it.

**Comment by mattzmsft** [comment]
@bradweiers thanks for the updates! one last question for you: in the porting article, a line reads "Please note that you should stay on the latest LTS release (any 20xx.4 release) for Windows MR." is that accurate? are all LTS releases versioned with .4?

**Comment by bradweiers** [comment]
Yes all LTS releases are .4 versions for the foreseeable future

**Comment by mattzmsft** [comment]
Got it. Thanks for clarifying!

**Pull request merged**
