### PR TITLE
Azure Cloud Tutorials

### PR DESCRIPTION
**Pull request by varunsiddaraju**
Updated links to unity release packages.

### CODE REVIEW

**Comment by mr0ng** [comment]
@jessemcculloch

**Comment by hferrone** [comment]
@mr0ng Have these gone through the Flesche readability score check?

**Comment by mr0ng** [comment]
@hferrone here are the readability results: 
image

**Comment by hferrone** [comment]
@jessemcculloch This one's ready too!

**Comment by jessemcculloch** [comment]
@mr0ng @varunsiddaraju - There are merge conflicts that need to be resolved on this one

**Comment by varunsiddaraju** [comment]
@jessemcculloch Resolved all merge conflicts.

**Pull request merged**
