### PR TITLE
Unreal Spatial Sound

### PR DESCRIPTION
**Pull request by hferrone**

### CODE REVIEW

**Comment by jessemcculloch** [comment]
Hey @hferrone, it looks like the doc is named unreal-spatial-sound.md but the link in the TOC is to unreal-spatial-audio.md

**Comment by sw5813** [comment]
A few minor edits: 

- "**You're** new sound asset will be created with a Details and all the spatial sound settings you could ask for:"- "you're" should be "your"
- The first heading should probably be "Installing **the** Microsoft Spatial Sound plugin"
- The second heading should probably be "Setting **the** spatialization..."

**Comment by NoelCross** [comment]
It would be good to update unreal-spatial-audio-img-02.png to reflect that the platform "HoloLens" should be selected in the left column to ensure that the settings are made for the correct platform.  It's also good to set for "Windows" as well for previewing in the editor.

**Comment by NoelCross** [comment]
Highlight Spatialization Method in unreal-spatial-audio-img-03.png

**Pull request merged**
