### PR TITLE
PC Holographic Remoting Tutorials

### PR DESCRIPTION
**Pull request by varunsiddaraju**
Improved tutorial grammar and format.

### CODE REVIEW

**Comment by mr0ng** [comment]
@jessemcculloch

**Comment by hferrone** [comment]
@mr0ng Have these gone through the Flesche readability score check?

**Comment by mr0ng** [comment]
@hferrone Here are the readability score results: 
image

**Comment by hferrone** [comment]
@jessemcculloch This is ready for merging!

**Pull request merged**
